Add event entries
CalConnect/calconnect.org pull request #33
Opened 2024-12-09 14:37 UTC by MuhammadAhsan252

close #19

2024-12-10 15:37 UTC, ronaldtse commented on _events/upcoming-virtual-events-planned.adoc
> +
Missing lots of content here:

https://www.calconnect.org/events/upcoming-virtual-events-planned
<img width="686" alt="Screenshot 2024-12-10 at 4 36 59 PM" src="https://github.com/user-attachments/assets/9f9ec926-ced6-4018-8a63-c19557c1765f">

2024-12-10 15:43 UTC, ronaldtse approved these changes
Lots of information missing on the event pages! You can just implement the tabs as sections on the same page. But all the information needs to be here.

2024-12-10 15:44 UTC, ronaldtse requested changes
Need to fill in all the event pages with details.

2024-12-11 21:49 UTC, ronaldtse commented
@MuhammadAhsan252 this PR is very very confusing. It seems that you used some AI processing to summarize the content?? We do not want any post-processing. We only want the original data.

2024-12-12 01:48 UTC, MuhammadAhsan252 commented
@ronaldtse In the latest commits, I only used Coradoc to covert HTML to Asciidoc. Afterwards I did some manual edits required for links and content. Other than that there was no post-processing done.

2024-12-13 04:03 UTC, merged